version: "3.9"

services:
  web:
    build: .
    image: volweb-app
    container_name: volweb-app
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NODE_ENV=production
      - SESSION_SECRET="124afasf"
    volumes:
      - type: bind
        source: ./Ilastik/ilastik
        target: /app/modules/ilastik
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - volweb-network
    restart: unless-stopped
    command: ["conda", "run", "--no-capture-output", "-n", "volweb", "npm", "start", "8080", "0.0.0.0"]

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - DOMAIN_NAME=_ 
    networks:
      - volweb-network

networks:
  volweb-network:
    driver: bridge

